##########
---
name: Docker Image CI
on:
  push:
    branches: [ "action-fail" ]
  pull_request:
    branches: [ "main" ]
jobs:
  unit_test:
    name: Maven Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run unit test
      run: |
        echo "mvn test"
  json_lint:
    name: Json lint
    needs: unit_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run unit test
      run: |
        chmod +x json-scan.sh
        ./json-scan.sh
  tf_lint:
    name: Tf lint
    needs: unit_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run unit test
      run: |
        chmod +x tf-lint.sh
        ./tf-lint.sh
  lint_scan:
    name: Lint scan
    needs: unit_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run unit test
      run: |
        chmod +x lint-scan.sh
        ./lint-scan.sh
  build:
    runs-on: ubuntu-latest
    needs: [lint_scan,tf_lint]
    steps:
    - uses: actions/checkout@v3
    - name: search
      run: |
        chmod +x scan.sh
        ./scan.sh
