name: Docker Image CI

on:
  push:
    branches: [ "action-fail" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  unit_test:
    name: Maven Unit Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: run unit test
      run: echo "mvn test"

  build:

    runs-on: ubuntu-latest
    needs: unit_test
    steps:
    - uses: actions/checkout@v3
    - name: search
      run: |
        chmod +x scan.sh
        ./scan.sh
